In [74]:
import torch
from torch import nn
from torch.nn import functional


class Inception(nn.Module):
    "We need to go deeper"
    def __init__(self, c1, c2, c3, c4):
        super(Inception, self).__init__()
        # 1. Branch 1
        self.b1_1 = nn.LazyConv2d(c1, kernel_size=1)
        # 2. Branch 2
        self.b2_1 = nn.LazyConv2d(c2[0], kernel_size=1)
        self.b2_2 = nn.LazyConv2d(c2[1], kernel_size=3, padding=1)
        # 2. Branch 3
        self.b3_1 = nn.LazyConv2d(c3[0], kernel_size=1)
        self.b3_2 = nn.LazyConv2d(c3[1], kernel_size=5, padding=2)
        # 2. Branch 4
        self.b4_1 = nn.MaxPool2d( kernel_size=3, stride=1,padding=1)
        self.b4_2 = nn.LazyConv2d(c4, kernel_size=1)

    def forward(self, x):
        bn1 = F.relu(self.b1_1(x))
        bn2 = F.relu(self.b2_1(F.relu(self.b2_2(x))))
        bn3 = F.relu(self.b3_1(F.relu(self.b3_2(x))))
        bn4 = F.relu(self.b4_1(F.relu(self.b4_2(x))))
        return torch.cat((bn1, bn2, bn3, bn4), dim=1)

In [67]:
X = torch.rand(1,1,96,96)

In [59]:
b1_1 = nn.LazyConv2d(96, kernel_size=1)

A:\huan_shit\Study_Shit\Deep_Learning\Dive_into_Deep_Learning\venv\lib\site-packages\torch\nn\modules\lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [60]:
F.relu(b1_1(X))

tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.5423, 0.4101, 0.0000,  ..., 0.4557, 0.4850, 0.0000],
          [0.4090, 0.4202, 0.0393,  ..., 0.0542, 0.4327, 0.1058],
          [0.0000, 0.5996, 0.2427,  ..., 0.4738, 0.0000, 0.4490],
          ...,
          [0.0000, 0.4866, 0.2158,  ..., 0.1641, 0.1960, 0.1088],
          [0.4184, 0.3197, 0.4327,  ..., 0.0000, 0.1955, 0.3616],
          [0.0000, 0.0460, 0.0000,  ..., 0.4556, 0.0736, 0.0000]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0

In [75]:
X = torch.rand(1, 1,96,96)
model = Inception(256, (160, 320), (32, 128), 128)

A:\huan_shit\Study_Shit\Deep_Learning\Dive_into_Deep_Learning\venv\lib\site-packages\torch\nn\modules\lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [76]:
model(X)

tensor([[[[1.1698, 1.4896, 1.2388,  ..., 1.5423, 1.5226, 1.3114],
          [1.3956, 0.8639, 1.6647,  ..., 1.2657, 1.2344, 1.0499],
          [1.5574, 0.9395, 1.1629,  ..., 1.0868, 1.2446, 1.4519],
          ...,
          [1.0377, 1.1413, 1.6226,  ..., 1.1727, 0.9363, 1.0025],
          [1.3389, 1.1335, 1.3113,  ..., 1.3994, 1.4748, 1.5740],
          [0.8460, 1.4038, 1.3191,  ..., 1.4719, 0.8545, 0.9190]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.1978, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.1150, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0074, 0.0000, 0.0000,  ..., 0.0000, 0.1185, 0.0460],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.2173, 0.0000, 0.0000,  ..., 0.0000, 0.2080, 0.1374]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0

In [64]:
class Inception2(nn.Module):
    # `c1`--`c4` are the number of output channels for each branch
    def __init__(self, c1, c2, c3, c4, **kwargs):
        super(Inception2, self).__init__(**kwargs)
        # Branch 1
        self.b1_1 = nn.LazyConv2d(c1, kernel_size=1)
        # Branch 2
        self.b2_1 = nn.LazyConv2d(c2[0], kernel_size=1)
        self.b2_2 = nn.LazyConv2d(c2[1], kernel_size=3, padding=1)
        # Branch 3
        self.b3_1 = nn.LazyConv2d(c3[0], kernel_size=1)
        self.b3_2 = nn.LazyConv2d(c3[1], kernel_size=5, padding=2)
        # Branch 4
        self.b4_1 = nn.MaxPool2d(kernel_size=3, stride=1, padding=1)
        self.b4_2 = nn.LazyConv2d(c4, kernel_size=1)

    def forward(self, x):
        b1 = F.relu(self.b1_1(x))
        b2 = F.relu(self.b2_2(F.relu(self.b2_1(x))))
        b3 = F.relu(self.b3_2(F.relu(self.b3_1(x))))
        b4 = F.relu(self.b4_2(self.b4_1(x)))
        return torch.cat((b1, b2, b3, b4), dim=1)

In [65]:
model2 = Inception2(256, (160, 320), (32, 128), 128)
model2(X)

A:\huan_shit\Study_Shit\Deep_Learning\Dive_into_Deep_Learning\venv\lib\site-packages\torch\nn\modules\lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0

In [30]:
import torch.nn as nn
import torch.nn.functional as F

class NET1(nn.Module):
    def __init__(self):
        super(NET1, self).__init__()
        self.conv = nn.Conv2d(3, 16, 3, 1, 1)
        self.bn = nn.BatchNorm2d(16)
        self.re = nn.ReLU()  # Module activation function

    def foreward(self, x):
        out = self.conv(x)
        out = self.bn(x)
        out = self.re()
        return out


class NET2(nn.Module):
    def __init__(self):
        super(NET2, self).__init__()
        self.conv = nn.Conv2d(3, 16, 3, 1, 1)
        self.bn = nn.BatchNorm2d(16)

    def foreward(self, x):
        out = self.conv(x)
        out = self.bn(x)
        out = F.relu(out)  # function activation function
        return out


net1 = NET1()
net2 = NET2()
print(net1)
print(net2)

NET1(
  (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (bn): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (re): ReLU()
)
NET2(
  (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (bn): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)


In [91]:
import torch
from torch import nn
from torch.nn import functional as F


class Inception(nn.Module):
    """We need to go deeper"""

    def __init__(self, c1, c2, c3, c4):
        super(Inception, self).__init__()
        # 1. Branch 1
        self.b1_1 = nn.LazyConv2d(c1, kernel_size=1)
        # 2. Branch 2
        self.b2_1 = nn.LazyConv2d(c2[0], kernel_size=1)
        self.b2_2 = nn.LazyConv2d(c2[1], kernel_size=3, padding=1)
        # 2. Branch 3
        self.b3_1 = nn.LazyConv2d(c3[0], kernel_size=1)
        self.b3_2 = nn.LazyConv2d(c3[1], kernel_size=5, padding=2)
        # 2. Branch 4
        self.b4_1 = nn.MaxPool2d(kernel_size=3, stride=1, padding=1)
        self.b4_2 = nn.LazyConv2d(c4, kernel_size=1)

    def forward(self, X):
        bn1 = F.relu(self.b1_1(X))
        bn2 = F.relu(self.b2_1(F.relu(self.b2_2(X))))
        bn3 = F.relu(self.b3_1(F.relu(self.b3_2(X))))
        bn4 = F.relu(self.b4_1(F.relu(self.b4_2(X))))
        return torch.cat((bn1, bn2, bn3, bn4), dim=1)


class GoogLeNet(nn.Module):
    def __init__(self):
        super(GoogLeNet, self).__init__()
        self.net = nn.Sequential(self.block_1(),
                                 self.block_2(),
                                 self.block_3(),
                                 self.block_4())

    def block_1(self):
        """
        7x7 Conv2d ->> 3x3 MaxPool2d -> 1x1 Conv2d -> 3x3 Conv2d -> 3x3 MaxPool2d
        """
        b1 = nn.Sequential(
            nn.LazyConv2d(64, kernel_size=7, stride=2, padding=3), nn.ReLU(),
            nn.MaxPool2d(kernel_size=3, stride=2, padding=1),
            nn.LazyConv2d(64, kernel_size=1), nn.ReLU(),
            nn.LazyConv2d(92, kernel_size=3, padding=1), nn.ReLU(),
            nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        )
        return b1

    def block_2(self):
        """
        2 x Inception Block -> MaxPool2d
        """
        b2 = nn.Sequential(
            Inception(64, (96, 128), (16, 32), 32),
            Inception(128, (128, 192), (32, 96), 64),
            nn.MaxPool2d(kernel_size=3, stride=2, padding=1),
        )
        return b2


    def block_3(self):
        """
        5 x Inception Block -> MaxPool2d
        """
        b3 = nn.Sequential(
            Inception(192, (96, 208), (16, 48), 64),
            Inception(160, (112, 224), (24, 64), 64),
            Inception(128, (128, 256), (24, 64), 64),
            Inception(112, (144, 288), (32, 64), 64),
            Inception(256, (160, 320), (32, 128), 128),
            nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        )
        return b3

    def block_4(self):
        """
        2 x Inception Block -> AvgPool -> FC
        """
        b4 = nn.Sequential(
            Inception(256, (160, 320), (32, 128), 128),
            Inception(384, (192, 384), (48, 128), 128),
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
            nn.LazyLinear(10),
        )
        return b4

    def forward(self, X):
        X = self.net(X)
        return X

    def layer_summary(self, X_shape):
        X = torch.rand((1, 1, 96, 96))
        for layer in self.net:
            X = layer(X)
            print(layer.__class__.__name__, "Output shape:", X.shape)






In [92]:
model = GoogLeNet()
X = torch.rand(1, 1,96, 96)

In [93]:
model(X)

tensor([[-0.0404,  0.0594,  0.0210,  0.0421,  0.0283, -0.0346,  0.0157,  0.0027,
          0.0171,  0.0023]], grad_fn=<AddmmBackward0>)

In [94]:
model.layer_summary((1, 1,96, 96))

Sequential Output shape: torch.Size([1, 92, 12, 12])
Sequential Output shape: torch.Size([1, 352, 6, 6])
Sequential Output shape: torch.Size([1, 576, 3, 3])
Sequential Output shape: torch.Size([1, 10])
